// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMo2rJlrv4750wzpaRQm8JpNSvhjNDiBs',
    appId: '1:551338757670:web:58a764b1a4ff65603ee0e7',
    messagingSenderId: '551338757670',
    projectId: 'tourapp-66e02',
    authDomain: 'tourapp-66e02.firebaseapp.com',
    storageBucket: 'tourapp-66e02.firebasestorage.app',
    measurementId: 'G-LF2S5Z33MZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClK8UnzBHBISfOu0IfBL0MD2hOsOCNGQQ',
    appId: '1:551338757670:android:abd35ace9d25215b3ee0e7',
    messagingSenderId: '551338757670',
    projectId: 'tourapp-66e02',
    storageBucket: 'tourapp-66e02.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUElNAVky8lIcZLBDPKOdc-irdlMVVQKU',
    appId: '1:551338757670:ios:9316df14c8e662633ee0e7',
    messagingSenderId: '551338757670',
    projectId: 'tourapp-66e02',
    storageBucket: 'tourapp-66e02.firebasestorage.app',
    androidClientId:
        '551338757670-6t6ddgtkot2ci7srllunlbl4pig33gnq.apps.googleusercontent.com',
    iosClientId:
        '551338757670-2nc6lpffpb5cc8lgm9qc6hu2rj1bqqui.apps.googleusercontent.com',
    iosBundleId: 'com.traveltech.guideManager',
  );
}
