// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiT_WPPU_qZd_Lx2evYwJs4laoHwCHBng',
    appId: '1:551338757670:web:38794bc88ad9bdc03ee0e7',
    messagingSenderId: '551338757670',
    projectId: 'tourapp-66e02',
    authDomain: 'tourapp-66e02.firebaseapp.com',
    storageBucket: 'tourapp-66e02.firebasestorage.app',
    measurementId: 'G-08SX79DMX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClK8UnzBHBISfOu0IfBL0MD2hOsOCNGQQ',
    appId: '1:551338757670:android:bd13b55d9b0a74ae3ee0e7',
    messagingSenderId: '551338757670',
    projectId: 'tourapp-66e02',
    storageBucket: 'tourapp-66e02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUElNAVky8lIcZLBDPKOdc-irdlMVVQKU',
    appId: '1:551338757670:ios:0903df1645fcb8ee3ee0e7',
    messagingSenderId: '551338757670',
    projectId: 'tourapp-66e02',
    storageBucket: 'tourapp-66e02.firebasestorage.app',
    iosBundleId: 'com.traveltech.guideManager',
  );
}
